const ALL_PRODUCTS = [
	{
		id: 1,
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		image: 'images/thumb-bananas.png',
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 2,
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
		image: 'images/thumb-biscuits.png',
	},
	{
		id: 3,
		image: 'images/thumb-cucumber.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 4,
		image: 'images/thumb-milk.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 5,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 6,
		image: 'images/thumb-biscuits.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 7,
		image: 'images/thumb-cucumber.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 8,
		image: 'images/thumb-milk.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 9,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 10,
		image: 'images/thumb-biscuits.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
]

const FRUITS_AND_VEGES = [
	{
		id: 11,
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		image: 'images/thumb-cucumber.png',
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 12,
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
		image: 'images/thumb-milk.png',
	},
	{
		id: 13,
		image: 'images/thumb-orange-juice.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 14,
		image: 'images/thumb-raspberries.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 15,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 16,
		image: 'images/thumb-biscuits.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
]

const JUICES = [
	{
		id: 17,
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		image: 'images/thumb-cucumber.png',
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 18,
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
		image: 'images/thumb-milk.png',
	},
	{
		id: 19,
		image: 'images/thumb-tomatoes.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 20,
		image: 'images/thumb-tomatoketchup.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 21,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 22,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
]

const BEST_SELL_PRODUCTS = [
	{
		id: 23,
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		image: 'images/thumb-tomatoes.png',
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 24,
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
		image: 'images/thumb-tomatoketchup.png',
	},
	{
		id: 25,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 26,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 27,
		image: 'images/thumb-tomatoes.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 28,
		image: 'images/thumb-tomatoketchup.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 29,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 30,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
]

const MOST_POPULAR_PRODUCTS = [
	{
		id: 31,
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		image: 'images/thumb-tomatoes.png',
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 32,
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
		image: 'images/thumb-tomatoketchup.png',
	},
	{
		id: 33,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 34,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 35,
		image: 'images/thumb-tomatoes.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 36,
		image: 'images/thumb-tomatoketchup.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 37,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 38,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
]

const JUST_ARRIVED_PRODUCTS = [
	{
		id: 39,
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		image: 'images/thumb-tomatoes.png',
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 40,
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
		image: 'images/thumb-tomatoketchup.png',
	},
	{
		id: 41,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 42,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 43,
		image: 'images/thumb-tomatoes.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 44,
		image: 'images/thumb-tomatoketchup.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 45,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 46,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
]

export default {
	ALL_PRODUCTS,
	FRUITS_AND_VEGES,
	JUICES,
	BEST_SELL_PRODUCTS,
	MOST_POPULAR_PRODUCTS,
	JUST_ARRIVED_PRODUCTS,
}
