const PRODUCTS = [
	{
		id: 1,
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		image: 'images/thumb-bananas.png',
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 2,
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
		image: 'images/thumb-biscuits.png',
	},
	{
		id: 3,
		image: 'images/thumb-cucumber.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 4,
		image: 'images/thumb-milk.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 5,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 6,
		image: 'images/thumb-biscuits.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 7,
		image: 'images/thumb-cucumber.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 8,
		image: 'images/thumb-milk.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 9,
		image: 'images/thumb-bananas.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
	{
		id: 10,
		image: 'images/thumb-biscuits.png',
		name: 'Sunstar Fresh Melon Juice',
		price: 18,
		discount: 30,
		rating: 4.5,
		unit: '1 Unit',
	},
]

export default PRODUCTS
